# Generated by Django 3.2.9 on 2022-01-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterConfigModel',
            fields=[
                ('newsletterConfigId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(verbose_name='UserId')),
                ('deliveryTime', models.TextField(default='EVENING', verbose_name='Delivery time')),
                ('recurrenceType', models.TextField(default='WEEKLY', verbose_name='Recurrence type')),
                ('dayOfWeek', models.IntegerField(default=0, verbose_name='Day of week')),
                ('isEnabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
            ],
        ),
    ]