# Generated by Django 3.2.9 on 2022-10-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfoCardModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='UUID')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Url')),
                ('title', models.TextField(null=True, verbose_name='Title')),
                ('summary', models.TextField(null=True, verbose_name='Summary')),
                ('image', models.TextField(null=True, verbose_name='Image')),
                ('publish_date', models.TextField(null=True, verbose_name='Publish Date')),
                ('author', models.TextField(null=True, verbose_name='Author')),
                ('source', models.TextField(null=True, verbose_name='Source')),
                ('is_political', models.BooleanField(default=0, null=True, verbose_name='IsPolitical')),
                ('topic', models.TextField(null=True, verbose_name='Topic')),
                ('leftOpinionCardUUID', models.TextField(null=True, verbose_name='LeftOpinionCardUUID')),
                ('rightOpinionCardUUID', models.TextField(null=True, verbose_name='RightOpinionCardUUID')),
                ('articleUrlList', models.TextField(null=True, verbose_name='ArticleUrlList')),
                ('articleTitleList', models.TextField(null=True, verbose_name='ArticleTitleList')),
            ],
        ),
        migrations.CreateModel(
            name='OpinionCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='UUID')),
                ('summary', models.TextField(null=True, verbose_name='Summary')),
                ('articleUrlList', models.TextField(null=True, verbose_name='ArticleUrlList')),
                ('articleTitleList', models.TextField(null=True, verbose_name='ArticleTitleList')),
            ],
        ),
    ]
