# Generated by Django 3.2.9 on 2022-10-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsInfoCard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionCardModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36, unique=True, verbose_name='UUID')),
                ('summary', models.TextField(null=True, verbose_name='Summary')),
                ('articleUrlList', models.TextField(null=True, verbose_name='ArticleUrlList')),
                ('articleTitleList', models.TextField(null=True, verbose_name='ArticleTitleList')),
            ],
        ),
        migrations.DeleteModel(
            name='OpinionCard',
        ),
        migrations.AlterField(
            model_name='newsinfocardmodel',
            name='leftOpinionCardUUID',
            field=models.CharField(max_length=36, null=True, verbose_name='LeftOpinionCardUUID'),
        ),
        migrations.AlterField(
            model_name='newsinfocardmodel',
            name='rightOpinionCardUUID',
            field=models.CharField(max_length=36, null=True, verbose_name='RightOpinionCardUUID'),
        ),
        migrations.AlterField(
            model_name='newsinfocardmodel',
            name='uuid',
            field=models.CharField(max_length=36, unique=True, verbose_name='UUID'),
        ),
    ]
