# Generated by Django 3.2.9 on 2022-11-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsInfoCard', '0003_newsinfocardmodel_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsInfoCardInteractionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36, unique=True, verbose_name='UUID')),
                ('newsInfoCardUUID', models.CharField(max_length=36, verbose_name='NewsInfoCardUUID')),
                ('interaction', models.TextField(null=True, verbose_name='Interaction')),
            ],
        ),
    ]
