# Generated by Django 3.2.9 on 2022-11-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsInfoCard', '0004_usernewsinfocardinteractionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernewsinfocardinteractionmodel',
            name='userUUID',
            field=models.CharField(max_length=36, null=True, verbose_name='UserUUID'),
        ),
    ]
