# Generated by Django 3.2.9 on 2022-11-01 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36, unique=True, verbose_name='UUID')),
                ('name', models.TextField(max_length=256, verbose_name='Name')),
                ('image', models.TextField(null=True, verbose_name='Image')),
                ('backgroundImage', models.TextField(null=True, verbose_name='BackgroundImage')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('locationUUID', models.CharField(max_length=36, verbose_name='LocationUUID')),
                ('createdAt', models.TextField(default=datetime.datetime.now, verbose_name='CreatedAt')),
                ('url', models.TextField(null=True, verbose_name='Url')),
                ('email', models.TextField(null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedOrgsForNewsInfoCardModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36, unique=True, verbose_name='UUID')),
                ('newsInfoCardUUID', models.CharField(max_length=36, null=True, verbose_name='newsInfoCardUUID')),
                ('organizationUUID', models.CharField(max_length=36, null=True, verbose_name='organizationUUID')),
                ('rank', models.IntegerField(null=True, verbose_name='rank')),
            ],
        ),
    ]
