# Generated by Django 3.2.9 on 2022-07-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Url')),
                ('title', models.TextField(verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.TextField(verbose_name='Image')),
                ('publish_date', models.TextField(null=True, verbose_name='Publish Date')),
                ('author', models.TextField(null=True, verbose_name='Author')),
                ('polarization_score', models.FloatField(null=True, default=0, verbose_name='Polarity')),
                ('topic', models.TextField(null=True, verbose_name='Topic')),
                ('parent_topic', models.TextField(null=True, verbose_name='ParentTopic')),
                ('top_passage', models.TextField(null=True,verbose_name='TopPassage')),
                ('top_fact', models.TextField(null=True, verbose_name='TopFact')),
            ],
        ),
    ]
