# Generated by Django 3.2.8 on 2021-11-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Url')),
                ('title', models.TextField(verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.TextField(verbose_name='Image')),
                ('publish_date', models.TextField(blank=True, null=True, verbose_name='Publish Date')),
                ('author', models.TextField(verbose_name='Author')),
            ],
        ),
    ]
