# Generated by Django 3.2.9 on 2021-12-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Url')),
                ('title', models.TextField(verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.TextField(null=True, verbose_name='Image')),
                ('publish_date', models.TextField(blank=True, null=True, verbose_name='Publish Date')),
                ('author', models.TextField(null=True, verbose_name='Author')),
                ('polarization_score', models.FloatField(default=0, null=True, verbose_name='Polarity')),
                ('primary_topic', models.TextField(null=True, verbose_name='PrimaryTopic')),
                ('sub_topic', models.TextField(null=True, verbose_name='SubTopic')),
            ],
        ),
    ]
