# Generated by Django 3.2.9 on 2022-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleRec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=models.TextField(verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='parent_topic',
            field=models.TextField(verbose_name='ParentTopic'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='polarization_score',
            field=models.FloatField(default=0, verbose_name='Polarity'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='top_fact',
            field=models.TextField(verbose_name='TopFact'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='top_passage',
            field=models.TextField(verbose_name='TopPassage'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='topic',
            field=models.TextField(verbose_name='Topic'),
        ),
    ]
