# Generated by Django 2.2 on 2021-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleRec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=models.TextField(null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.TextField(null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='polarization',
            field=models.BooleanField(default=0, null=True, verbose_name='Polarity'),
        ),
    ]
