# Generated by Django 3.2.9 on 2021-12-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleRec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='primary_topic',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='sub_topic',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='parent_topic',
            field=models.TextField(null=True, verbose_name='ParentTopic'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='top_fact',
            field=models.TextField(null=True, verbose_name='TopFact'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='top_passage',
            field=models.TextField(null=True, verbose_name='TopPassage'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='topic',
            field=models.TextField(null=True, verbose_name='Topic'),
        ),
    ]
