# Generated by Django 2.2 on 2021-11-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleRec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='polarization',
            field=models.BooleanField(default=0, verbose_name='Polarity'),
        ),
    ]
