# Generated by Django 3.2.9 on 2022-10-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleRec', '0002_auto_20220616_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='author',
            field=models.TextField(null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.TextField(null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='parent_topic',
            field=models.TextField(null=True, verbose_name='ParentTopic'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='polarization_score',
            field=models.FloatField(default=0, null=True, verbose_name='Polarity'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='top_fact',
            field=models.TextField(null=True, verbose_name='TopFact'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='top_passage',
            field=models.TextField(null=True, verbose_name='TopPassage'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='topic',
            field=models.TextField(null=True, verbose_name='Topic'),
        ),
    ]
