# Generated by Django 3.2.9 on 2021-12-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleRec', '0002_auto_20211214_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='primary_topic',
            field=models.IntegerField(null=True, verbose_name='PrimaryTopic'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='sub_topic',
            field=models.IntegerField(null=True, verbose_name='SubTopic'),
        ),
    ]
