# Generated by Django 3.2.9 on 2021-12-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleRec', '0003_auto_20211219_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='polarization',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='polarization_score',
            field=models.FloatField(default=0, null=True, verbose_name='Polarity'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='primary_topic',
            field=models.TextField(null=True, verbose_name='PrimaryTopic'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='sub_topic',
            field=models.TextField(null=True, verbose_name='SubTopic'),
        ),
    ]
