

rss_feeds = [
	# Tech
	{"url":"https://techcrunch.com/feed/", "source":"Tech Crunch", "category":"Tech"},
	{"url":"https://www.technologyreview.com/feed/", "source":"TechReview", "category":"Tech"},
	{"url":"http://feeds.arstechnica.com/arstechnica/technology-lab", "source":"Ars Technica", "category":"Tech"},
	{"url":"http://feeds.feedburner.com/venturebeat/SZYF", "source":"Venture Beat", "category":"Tech"},
	{"url":"https://www.vox.com/rss/recode/index.xml", "source":"Vox", "category":"Tech"},
	{"url":"https://www.wired.com/feed/rss", "source":"Wired", "category":"Tech"},
	{"url":"http://feeds.feedburner.com/IeeeSpectrumFullText", "source":"IEEE", "category":"Tech"},
	{"url":"https://www.cnet.com/rss/news/", "source":"CNet", "category":"Tech"},
	{"url":"https://www.theverge.com/rss/frontpage", "source":"The Verge", "category":"Tech"},
	{"url":"https://markets.businessinsider.com/rss/news", "source":"Business Insider", "category":"Tech"},
	{"url":"https://www.techspot.com/backend.xml", "source":"TechSpot", "category":"Tech"},
	{"url":"https://cdn.hackernoon.com/feed", "source":"HackerNoon", "category":"Tech"},
	{"url":"https://appleinsider.com/rss/news/", "source":"Apple Insider", "category":"Tech"},
	{"url":"https://thenextweb.com/topic/tech", "source":"The Next Web", "category":"Tech"},
	{"url":"https://www.geekwire.com/feed/", "source":"Geek Wire", "category":"Tech"},
	# General
	{"url":"https://www.latimes.com/local/rss2.0.xml", "source":"LA Times", "category":"Local"},
	{"url":"http://rss.cnn.com/rss/cnn_topstories.rss", "source":"CNN", "category":"Global"},
	{"url":"https://www.huffpost.com/section/front-page/feed?x=1", "source":"Huffington Post", "category":"Global"},
	{"url":"http://rssfeeds.usatoday.com/UsatodaycomNation-TopStories", "source":"USA Today", "category":"Top Stories"},
	{"url":"http://feeds.foxnews.com/foxnews/latest", "source":"Fox News", "category":"Top Stories"},
	{"url":"http://feeds.foxnews.com/foxnews/national", "source":"Fox News", "category":"National"},
	{"url":"http://feeds.foxnews.com/foxnews/world", "source":"Fox News", "category":"World"},
	{"url":"http://feeds.foxnews.com/foxnews/politics", "source":"Fox News", "category":"Politics"},
	{"url":"http://feeds.foxnews.com/foxnews/scitech", "source":"Fox News", "category":"Tech"},
	{"url":"http://feeds.foxnews.com/foxnews/health", "source":"Fox News", "category":"Health"},
	{"url":"http://feeds.foxnews.com/foxnews/entertainment", "source":"Entertainment", "category":"Entertainment"},
	{"url":"http://feeds.foxnews.com/foxnews/views", "source":"Fox News", "category":"Opinion"},
	{"url":"http://breitbart.com/world-news", "source":"Breitbart", "category":"World News"},
	{"url":"http://breitbart.com/politics", "source":"Breitbart", "cateogry":"Politics"},
	{"url":"http://breitbart.com/economy", "source":"Breitbart", "category":"Economy"},
	{"url":"http://breitbart.com/tech", "source":"Breitbart", "category":"Tech"},
	{"url":"http://breitbart.com/europe", "source":"Breitbart", "category":"World"},
	{"url":"http://breitbart.com/asia", "source":"Breitbart", "category":"Asia"},
	{"url":"http://breitbart.com/latin-america","source":"Breitbart","category":"World"},
	{"url":"http://breitbart.com/africa", "source":"Breitbart","category":"World"},
	{"url":"http://breitbart.com/middle-east", "source":"Breitbart", "category":"World"},
	{"url":"https://www.washingtontimes.com/rss/headlines/opinion/advocacy/", "source":"Washington Times", "category":"Opinion"},
	{"url":"https://www.washingtontimes.com/rss/headlines/opinion/political-theater/", "source":"Washington Times", "category":"Opinion"},
	{"url":"https://www.washingtontimes.com/rss/headlines/news/analysis/", "source":"Washington Times", "category":"Top Stories"},
	{"url":"https://www.washingtontimes.com/rss/headlines/news/business-economy/", "source":"Washington Times", "category":"Business"},
	{"url":"https://www.washingtontimes.com/rss/headlines/news/inside-politics/", "source":"Washington Times", "category":"Politics"},
	{"url":"https://www.washingtontimes.com/rss/headlines/news/inside-china/", "source":"Washington Times", "category":"World"},
	{"url":"https://www.washingtontimes.com/rss/headlines/news/politics/", "source":"Washington Times", "category":"Politics"},
  {"url":"https://thehill.com/taxonomy/term/1116/feed", "source":"The Hill", "category":""},
  {"url":"https://thehill.com/rss/syndicator/19110", "source":"The Hill"},
  {"url":"https://thehill.com/rss/syndicator/19109", "source":"The Hill"},
  {"url":"https://thehill.com/taxonomy/term/43/feed", "source":"The Hill"},
  {"url":"https://thehill.com/taxonomy/term/27/feed", "source":"The Hill"},
  {"url":"https://thehill.com/taxonomy/term/38/feed", "source":"The Hill"},
  {"url":"https://thehill.com/taxonomy/term/33/feed", "source":"The Hill"},
  {"url":"https://thehill.com/taxonomy/term/30/feed", "source":"The Hill"},
  {"url":"https://thehill.com/taxonomy/term/28/feed","source":"The Hill"},
  {"url":"https://thehill.com/taxonomy/term/39/feed","source":"The Hill"},
  {"url":"https://thehill.com/taxonomy/term/49/feed","source":"The Hill"},
  {"url":"https://thehill.com/taxonomy/term/20/feed","source":"The Hill"},
  {"url":"https://rsshub.app/apnews/topics/apf-topnews","source":"AP News"},
  {"url":"https://feeds.npr.org/1001/rss.xml","source":"NPR"},
  {"url":"https://rss.nytimes.com/services/xml/rss/nyt/US.xml", "source":"NY Times"},
	{"url":"https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml", "source":"NY Times"},
	{"url":"https://rss.nytimes.com/services/xml/rss/nyt/Business.xml", "source":"NY Times"},
	{"url":"https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml", "source":"NY Times"},
	{"url":"https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml", "source":"NY Times"},
	{"url":"https://rss.nytimes.com/services/xml/rss/nyt/US.xml", "source": "NY Times"},
	{"url":"https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", "source":"NY Times"},
	{"url":"http://feeds.washingtonpost.com/rss/politics", "source":"Washington Post"},
	{"url":"http://feeds.washingtonpost.com/rss/opinion", "source":"Washington Post"},
	{"url":"http://feeds.washingtonpost.com/rss/world", "source":"Washington Post"},
	{"url":"http://feeds.washingtonpost.com/rss/business", "source":"Washington Post"},
	{"url":"https://www.foxnews.com/about/rss/politics", "source":"Fox News"},
	{"url":"http://rss.cnn.com/rss/cnn_world.rss", "source":"CNN"},
	{"url":"http://rss.cnn.com/rss/cnn_us.rss", "source":"CNN"},
	{"url":"http://rss.cnn.com/rss/cnn_allpolitics.rss", "source":"CNN"},
	{"url":"http://rss.cnn.com/rss/cnn_tech.rss", "source":"CNN"},
	{"url":"https://www.nationalreview.com/corner/feed/", "source":"National Review"},
	{"url":"https://feeds.a.dj.com/rss/RSSOpinion.xml",  "source":"AlJazeera"},
	{"url":"https://feeds.a.dj.com/rss/RSSWorldNews.xml", "source":"AlJazeera"},
	{"url":"https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml", "source":"AlJazeera"},
	{"url":"https://feeds.a.dj.com/rss/RSSMarketsMain.xml", "source":"AlJazeera"},
	{"url":"https://feeds.a.dj.com/rss/RSSWSJD.xml", "source":"AlJazeera"},
	{"url":"http://feeds.bbci.co.uk/news/business/rss.xml", "source":"BBC"},
	{"url":"http://feeds.bbci.co.uk/news/politics/rss.xml","source":"BBC"},
	{"url":"http://feeds.bbci.co.uk/news/world/rss.xml", "source":"BBC"},
	{"url":"http://feeds.bbci.co.uk/news/technology/rss.xml","source":"BBC"},
	{"url":"http://feeds.bbci.co.uk/news/science_and_environment/rss.xml", "source":"BBC"},
  {"url":"http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml?edition=int", "source":"BBC"},
	{"url":"https://rss.politico.com/economy.xml", "source":"Politico"},
	{"url":"https://rss.politico.com/politics-news.xml", "source":"Politico"},
	{"url":"https://rss.politico.com/congress.xml", "source":"Politico"},
	{"url":"https://rss.politico.com/healthcare.xml", "source":"Politico"},
	{"url":"https://rss.politico.com/defense.xml", "source":"Politico"},
	{"url":"https://rss.politico.com/energy.xml", "source":"Politico"},
	{"url":"https://fivethirtyeight.com/all/feed", "source":"Five Thirty Eight"},
	{"url":"https://www.vox.com/rss/index.xml", "source":"Vox"},
	{"url":"https://www.economist.com/special-report/rss.xml", "source":"Economist"},
  {"url":"https://www.economist.com/europe/rss.xml", "source":"Economist"},
  {"url":"https://www.economist.com/united-states/rss.xml", "source":"Economist"},
  {"url":"https://www.economist.com/asia/rss.xml", "source":"Economist"},
  {"url":"https://www.economist.com/middle-east-and-africa/rss.xml", "source":"Economist"},
  {"url":"https://www.economist.com/china/rss.xml", "source":"Economist"},
  {"url":"https://www.economist.com/international/rss.xml", "source":"Economist"},
  {"url":"https://www.economist.com/business/rss.xml", "source":"Economist"},
  {"url":"https://www.economist.com/finance-and-economics/rss.xml", "source":"Economist"},
  {"url":"https://www.economist.com/science-and-technology/rss.xml", "source":"Economist"},
]
