# Generated by Django 3.2.9 on 2021-12-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('topicId', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.TextField(verbose_name='Topic')),
                ('parentTopic', models.TextField(verbose_name='Parent topic')),
            ],
        ),
    ]
