# Generated by Django 3.2.9 on 2022-06-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicModeling', '0002_auto_20211231_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='createdAt',
            field=models.TextField(null=True, verbose_name='Publish Date'),
        ),
    ]
