# Generated by Django 3.2.9 on 2022-06-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPageModel',
            fields=[
                ('topicPageId', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('topicId', models.IntegerField(verbose_name='TopicId')),
                ('summary', models.TextField(verbose_name='Text')),
                ('title', models.TextField(verbose_name='Text')),
                ('imageURL', models.TextField(verbose_name='Text')),
                ('urls', models.TextField(verbose_name='Urls')),
                ('topArticleId', models.IntegerField(verbose_name='TopArticleId')),
                ('isTimeline', models.BooleanField(verbose_name='IsTimeline')),
            ],
        ),
    ]
