# Generated by Django 3.2.9 on 2022-06-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpagemodel',
            name='topic',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
