# Generated by Django 3.2.9 on 2022-06-18 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicFeed', '0002_alter_topicpagemodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpagemodel',
            name='createdAt',
            field=models.TextField(default=datetime.datetime.now, verbose_name='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='topicpagemodel',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
