FROM mysql/mysql-server:8.0

COPY config-file.cnf /etc/mysql/my.cnf

# RUN cat ./docker/db/init_db.sh
# RUN cat /etc/my.cnf
# RUN cat /etc/mysql/mysql.conf.d/mysqld.cnf

# COPY ./docker/db/init_db.sh /docker-entrypoint-initdb.d/
# RUN chmod +x /docker-entrypoint-initdb.d/init_db.sh

# FROM mysql
# ADD script.sql /docker-entrypoint-initdb.d/script.sql
# RUN chmod -R 775 /docker-entrypoint-initdb.d

# ENV MYSQL_ROOT_PASSWORD mypass



