# Generated by Django 3.2.9 on 2021-12-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.TextField(verbose_name='First name')),
                ('lastName', models.TextField(verbose_name='Title')),
                ('email', models.TextField(verbose_name='Text')),
                ('firebaseAuthId', models.TextField(null=True, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='UserTopicModel',
            fields=[
                ('userTopicId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.TextField(verbose_name='UserId')),
                ('topic', models.TextField(verbose_name='Topic')),
            ],
        ),
    ]
