# Generated by Django 3.2.9 on 2021-12-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.TextField(verbose_name='First name')),
                ('lastName', models.TextField(verbose_name='Title')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('firebaseAuthId', models.TextField(null=True, verbose_name='FirebaseAuthId')),
            ],
        ),
        migrations.CreateModel(
            name='UserTopicModel',
            fields=[
                ('userTopicId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(null=True, verbose_name='UserId')),
                ('topicId', models.IntegerField(null=True, verbose_name='TopicId')),
            ],
            options={
                'unique_together': {('userId', 'topicId')},
            },
        ),
    ]
