# Generated by Django 3.2.9 on 2022-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPreferences', '0002_usertopicmodel_fornewsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertopicmodel',
            name='firebaseAuthId',
            field=models.TextField(null=True, verbose_name='FirebaseAuthId'),
        ),
    ]
