
# List of causes that tie organizations to news articles

causesList = [
  "Animal Protection & Welfare",
  "Animals",
  "Arts & Culture",
  "Printing & Publishing",
  "Arts Education",
  "Media & Communications",
  "Education",
  "Health",
  "Libraries",
  "Environment",
  "Natural Resources Conservation & Protection",
  "Wildlife Preservation & Protection",
  "International",
  "International Development",
  "Specifically Named Diseases",
  "Government & Public Administration",
  "Medical Research",
  "Mental Health",
  "Mental Health Treatment",
  "Children & Youth",
  "International Relief",
  "Scouting",
  "Group Homes",
  "Human Service Organizations",
  "Human Services",
  "Judaism",
  "Religion",
  "Cancer",
  "Counseling",
  "Protection of Endangered Species",
  "Community Health Systems",
  "Homeless & Housing",
  "Homeless Centers",
  "Cultural & Ethnic Awareness",
  "Democracy",
  "Youth Community Service Clubs",
  "Youth Development - Citizenship",
  "Health Care",
  "Philanthropy",
  "Private Grantmaking Foundations",
  "Public Health",
  "Bullying",
  "Educational Services",
  "Mental Health Associations",
  "Youth Development Programs",
  "Emergency Assistance",
  "Literacy",
  "Public Foundations",
  "Military & Veterans Organizations",
  "National Security",
  "Veterans",
  "Camps",
  "Voluntarism & Grantmaking Foundations",
  "Sports",
  "Citizen Participation",
]



